name: Coding Standards

on:
  push:
    branches:
      - develop
      - stable
      - release/**
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Script and Style Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log debug information
        run: |
          npm --version
          node --version
          git --version
      - name: Install NodeJS v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Log debug information
        run: |
          npm --version
          node --version
      - name: Install npm dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint:scripts
      - name: Run stylelint
        run: npm run lint:styles
      - name: Run npmPkgJsonLint
        run: npm run lint:pkg
  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr
      - name: Log debug information
        run: |
          php --version
          composer --version
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--no-progress --no-ansi --no-interaction"
      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH
      - name: Log PHPCS debug information
        run: phpcs -i
      - name: Run PHPCS
        run: phpcs -q -n --report=checkstyle | cs2pr
